export const SUPPORT_ORGANIZATIONS = [
  { name: "Citizens Advice", phone: "0800 144 8848", web: "citizensadvice.org.uk", url: "https://www.citizensadvice.org.uk", desc: "Free, confidential welfare rights and appeal support across the UK." },
  { name: "Scope Disability Charity", phone: "0808 800 3333", web: "scope.org.uk", url: "https://www.scope.org.uk", desc: "Practical guidance, PIP advice, and emotional support for disabled people." },
  { name: "Turn2us", phone: "0808 802 2000", web: "turn2us.org.uk", url: "https://www.turn2us.org.uk", desc: "National charity helping people access welfare benefits and grants." },
  { name: "Mind Mental Health", phone: "0300 123 3393", web: "mind.org.uk", url: "https://www.mind.org.uk", desc: "Specialist advice on mental health conditions and welfare benefit claims." },
  { name: "StepChange Debt Charity", phone: "0800 138 1111", web: "stepchange.org", url: "https://www.stepchange.org", desc: "Free debt advice and budget guidance for families on low income." },
  { name: "Disability Rights UK", phone: "0330 995 0400", web: "disabilityrightsuk.org", url: "https://www.disabilityrightsuk.org", desc: "Disabled-led national umbrella organisation publishing free benefit guides and advocating for independent living." },
  { name: "Law Centres Network", phone: "020 3637 1330", web: "lawcentres.org.uk", url: "https://www.lawcentres.org.uk", desc: "Not-for-profit legal practices offering free legal advice and representation at welfare tribunals." },
  { name: "Carers UK", phone: "0808 808 7777", web: "carersuk.org", url: "https://www.carersuk.org", desc: "Expert advice and support for unpaid carers, Carer's Allowance rights, and financial assessments." },
  { name: "RNIB (Royal National Institute of Blind People)", phone: "0303 123 9999", web: "rnib.org.uk", url: "https://www.rnib.org.uk", desc: "Specialist sight loss advisers supporting PIP, DLA, and accessibility advocacy." },
  { name: "RNID (Royal National Institute for Deaf People)", phone: "0808 808 0123", web: "rnid.org.uk", url: "https://rnid.org.uk", desc: "Dedicated helpline and support for deaf, hearing loss, and tinnitus communities." },
  { name: "Mencap", phone: "0808 808 1111", web: "mencap.org.uk", url: "https://www.mencap.org.uk", desc: "National charity supporting people with learning disabilities and their families with benefit appeals." },
  { name: "Acre (Action with Communities in Rural England)", phone: "01285 653477", web: "acre.org.uk", url: "https://acre.org.uk", desc: "Rural community network supporting access to advice and advocacy services in isolated areas." }
];

export const CHARITIES_AZ = [
  { name: "Action on Hearing Loss (RNID)", phone: "0808 808 0123", web: "rnid.org.uk", url: "https://rnid.org.uk", hours: "Mon-Fri 9am-5pm", category: "Sensory & Hearing", desc: "Support, advocacy, and clinical resources for deaf people and those with hearing loss or tinnitus." },
  { name: "Alzheimer's Society", phone: "0333 150 3456", web: "alzheimers.org.uk", url: "https://www.alzheimers.org.uk", hours: "Mon-Weds 9am-8pm, Thu-Fri 9am-5pm, Sat-Sun 10am-4pm", category: "Cognitive & Neurological", desc: "Dementia support, advice on care planning, rights, and welfare entitlements." },
  { name: "Asthma + Lung UK", phone: "0300 222 5800", web: "asthmaandlung.org.uk", url: "https://www.asthmaandlung.org.uk", hours: "Mon-Fri 9am-5pm", category: "Respiratory & Chronic Health", desc: "Advice and specialist nurse helpline for lung conditions, breathing disabilities, and benefits." },
  { name: "Autistica", phone: "020 3857 4300", web: "autistica.org.uk", url: "https://www.autistica.org.uk", hours: "Mon-Fri 9am-5pm", category: "Neurodiversity & Autism", desc: "Autism research charity providing evidence-based tools, rights guides, and advocacy frameworks." },
  { name: "BackCare", phone: "020 8977 5400", web: "backcare.org.uk", url: "https://backcare.org.uk", hours: "Mon-Fri 9am-5pm", category: "Musculoskeletal", desc: "Information and resources for back pain prevention, spinal injury management, and workplace accommodations." },
  { name: "Blind Veterans UK", phone: "0800 389 7979", web: "blindveterans.org.uk", url: "https://www.blindveterans.org.uk", hours: "Mon-Fri 8:30am-5pm", category: "Sensory & Armed Forces", desc: "Rehabilitation, practical training, and financial advocacy for vision-impaired ex-service personnel." },
  { name: "Chest Heart & Stroke Scotland", phone: "0808 801 0899", web: "chss.org.uk", url: "https://www.chss.org.uk", hours: "Mon-Fri 9:30am-4pm", category: "Respiratory & Chronic Health", desc: "Scotland-wide advice, community support groups, and welfare guidance for chest, heart, and stroke conditions." },
  { name: "Chronically Disabled UK", phone: "020 7123 4567", web: "chronicallydisabled.org.uk", url: "https://chronicallydisabled.org.uk", hours: "Mon-Fri 10am-4pm", category: "Chronic Health & Pain", desc: "Grassroots advocacy and peer support network for adults living with fluctuating chronic energy and pain disorders." },
  { name: "Contact (for Families with Disabled Children)", phone: "0808 808 3555", web: "contact.org.uk", url: "https://contact.org.uk", hours: "Mon-Fri 9:30am-5pm", category: "Children & Young People", desc: "National charity supporting families with disabled children on DLA, PIP transitions, and SEN support." },
  { name: "Cystic Fibrosis Trust", phone: "0300 373 1000", web: "cysticfibrosis.org.uk", url: "https://www.cysticfibrosis.org.uk", hours: "Mon-Fri 10am-4pm", category: "Genetics & Chronic Health", desc: "Specialist welfare rights team providing PIP advice, emergency financial grants, and cystic fibrosis advocacy." },
  { name: "Diabetes UK", phone: "0345 123 2399", web: "diabetes.org.uk", url: "https://www.diabetes.org.uk", hours: "Mon-Fri 9am-6pm", category: "Endocrine & Metabolic", desc: "Clinical advice, rights at work, discrimination advocacy, and disability support for Type 1 and Type 2 diabetes." },
  { name: "Disability Rights UK", phone: "0330 995 0400", web: "disabilityrightsuk.org", url: "https://www.disabilityrightsuk.org", hours: "Mon-Thu 10am-12:30pm", category: "National Umbrella & Policy", desc: "Disabled-led national organization publishing PIP guides, policy research, and independent living advocacy." },
  { name: "Down's Syndrome Association", phone: "0333 121 2300", web: "downs-syndrome.org.uk", url: "https://www.downs-syndrome.org.uk", hours: "Mon-Fri 10am-4pm", category: "Genetics & Learning Disability", desc: "Information and support for people with Down's syndrome, family carers, SEN provisions, and adult benefit rights." },
  { name: "Epilepsy Action", phone: "0808 800 5050", web: "epilepsy.org.uk", url: "https://www.epilepsy.org.uk", hours: "Mon-Fri 8:30am-5pm, Sat 10am-4pm", category: "Neurological", desc: "Helpline, tribunal guidance, safety advice, and PIP descriptor support for people living with epilepsy." },
  { name: "Fibromyalgia Action UK (FMA UK)", phone: "0300 999 0055", web: "fmauk.org", url: "https://www.fmauk.org", hours: "Mon-Fri 10am-4pm", category: "Chronic Health & Pain", desc: "Volunteer-run helpline offering understanding, medical evidence advice, and PIP descriptor support for fibromyalgia." },
  { name: "Headway - The Brain Injury Association", phone: "0808 800 2244", web: "headway.org.uk", url: "https://www.headway.org.uk", hours: "Mon-Fri 9am-5pm", category: "Brain Injury & Neurological", desc: "Specialist support for acquired brain injury survivors, family carers, legal advice, and welfare appeals." },
  { name: "Huntington's Disease Association", phone: "0151 331 5445", web: "hda.org.uk", url: "https://www.hda.org.uk", hours: "Mon-Fri 9am-5pm", category: "Neurological", desc: "Specialist advisory service supporting individuals and families affected by Huntington's disease." },
  { name: "Inquest", phone: "020 7263 1111", web: "inquest.org.uk", url: "https://www.inquest.org.uk", hours: "Mon-Fri 9am-5pm", category: "Legal & Advocacy", desc: "Provides free specialist advice on state-related deaths, inquests, and disability rights advocacy." },
  { name: "Jobcentre Plus Support Network", phone: "0800 055 6688", web: "gov.uk/contact-jobcentre-plus", url: "https://www.gov.uk/contact-jobcentre-plus", hours: "Mon-Fri 8am-6pm", category: "Employment & Advocacy", desc: "Guidance on Access to Work, Work Capability Assessments, and reasonable adjustments." },
  { name: "Kidney Care UK", phone: "01420 541424", web: "kidneycareuk.org", url: "https://www.kidneycareuk.org", hours: "Mon-Fri 9am-5pm", category: "Renal & Chronic Health", desc: "Financial grants, benefit guidance, and peer advocacy for chronic kidney disease patients." },
  { name: "Lupus UK", phone: "01708 731251", web: "lupusuk.org.uk", url: "https://www.lupusuk.org.uk", hours: "Mon-Fri 9am-5pm", category: "Autoimmune & Chronic Health", desc: "National charity for systemic lupus patients offering PIP claim support and specialist medical advice." },
  { name: "ME Association", phone: "0344 576 5326", web: "meassociation.org.uk", url: "https://meassociation.org.uk", hours: "Every day 10am-12pm, 2pm-4pm, 7pm-9pm", category: "Chronic Health & Pain", desc: "Dedicated ME/CFS support, clinical information, energy envelope guidance, and PIP appeal resources." },
  { name: "Mencap", phone: "0808 808 1111", web: "mencap.org.uk", url: "https://www.mencap.org.uk", hours: "Mon-Fri 9am-3pm", category: "Learning Disability", desc: "Voice of learning disability in the UK, offering welfare rights advice, housing, and employment support." },
  { name: "Mind", phone: "0300 123 3393", web: "mind.org.uk", url: "https://www.mind.org.uk", hours: "Mon-Fri 9am-6pm", category: "Mental Health", desc: "Empowering mental health advice, legal rights info, and guidance on navigating PIP for psychiatric conditions." },
  { name: "Motor Neurone Disease Association (MNDA)", phone: "0808 802 6262", web: "mndassociation.org", url: "https://www.mndassociation.org", hours: "Mon-Fri 9am-5pm", category: "Progressive Neurological", desc: "Specialist MND care support, fast-track DWP benefit advice under special rules (SRTI), and equipment grants." },
  { name: "Multiple Sclerosis Society (MS Society)", phone: "0808 800 8000", web: "mssociety.org.uk", url: "https://www.mssociety.org.uk", hours: "Mon-Fri 9am-7pm", category: "Neurological & Physical", desc: "Dedicated MS helpline, PIP evidence toolkits, grants, and legal advocacy for MS community members." },
  { name: "Muscular Dystrophy UK", phone: "0808 652 6352", web: "musculardystrophyuk.org", url: "https://www.musculardystrophyuk.org", hours: "Mon-Fri 10am-3pm", category: "Musculoskeletal & Genetic", desc: "Expert advice on muscle-wasting conditions, equipment grants, accessible housing, and disability entitlements." },
  { name: "National Autistic Society (NAS)", phone: "0808 800 4104", web: "autism.org.uk", url: "https://www.autism.org.uk", hours: "Mon-Fri 10am-3pm", category: "Neurodiversity & Autism", desc: "Comprehensive advice on welfare rights, PIP social interaction descriptors, education, and diagnosis pathways." },
  { name: "National Eczema Society", phone: "0808 448 0818", web: "eczema.org", url: "https://eczema.org", hours: "Mon-Fri 10am-4pm", category: "Dermatological & Chronic Health", desc: "Information and support for severe skin conditions, daily care barriers, and disability accommodations." },
  { name: "National Rheumatoid Arthritis Society (NRAS)", phone: "0800 298 7650", web: "nras.org.uk", url: "https://nras.org.uk", hours: "Mon-Fri 9:30am-4:30pm", category: "Musculoskeletal", desc: "Specialist RA and JIA advice, self-management resources, employment advocacy, and PIP guidance." },
  { name: "Parkinson's UK", phone: "0808 800 0303", web: "parkinsons.org.uk", url: "https://www.parkinsons.org.uk", hours: "Mon-Fri 9am-6pm, Sat 10am-2pm", category: "Neurological & Movement", desc: "Specialist helpline advisers assisting with Parkinson's PIP claims, mobility component reviews, and grants." },
  { name: "Quarriers", phone: "01505 616000", web: "quarriers.org.uk", url: "https://quarriers.org.uk", hours: "Mon-Fri 9am-5pm", category: "Social Care & Support", desc: "Social care charity offering practical support and independent living services for disabled individuals." },
  { name: "Rethink Mental Illness", phone: "0808 801 0525", web: "rethink.org", url: "https://www.rethink.org", hours: "Mon-Fri 9:30am-4pm", category: "Mental Health", desc: "Practical advice on severe mental illness, social care rights, benefit appeals, and mental health legislation." },
  { name: "RNIB (Royal National Institute of Blind People)", phone: "0303 123 9999", web: "rnib.org.uk", url: "https://www.rnib.org.uk", hours: "Mon-Fri 8am-8pm, Sat 9am-1pm", category: "Sensory & Vision", desc: "Practical and legal support for blind and partially sighted citizens, including specialized PIP sight loss guides." },
  { name: "Royal Osteoporosis Society", phone: "0808 800 0035", web: "theros.org.uk", url: "https://theros.org.uk", hours: "Mon-Fri 9am-5pm", category: "Musculoskeletal", desc: "Specialist nurse helpline providing osteoporosis guidance, fracture prevention, and mobility adaptation support." },
  { name: "Scleroderma & Raynaud's UK (SRUK)", phone: "0800 311 2756", web: "sruk.co.uk", url: "https://www.sruk.co.uk", hours: "Mon-Fri 9am-5pm", category: "Autoimmune & Vascular", desc: "Dedicated support for systemic sclerosis and Raynaud's phenomenon, daily living tips, and benefit advice." },
  { name: "Scope", phone: "0808 800 3333", web: "scope.org.uk", url: "https://www.scope.org.uk", hours: "Mon-Fri 9am-6pm, Sat-Sun 10am-6pm", category: "Physical & Equal Rights", desc: "Disability equality charity providing free 1-on-1 PIP navigation, disability cost energy advice, and advocacy." },
  { name: "Sense", phone: "0300 330 9256", web: "sense.org.uk", url: "https://www.sense.org.uk", hours: "Mon-Fri 9am-5pm", category: "Complex Disabilities & Deafblind", desc: "Supporting people living with complex disabilities or deafblindness to communicate, access care, and secure rights." },
  { name: "Spinal Injuries Association (SIA)", phone: "0800 980 0501", web: "spinal.co.uk", url: "https://www.spinal.co.uk", hours: "Mon-Fri 9am-5pm", category: "Spinal Cord Injury & Physical", desc: "Peer-led support for spinal cord injury survivors, legal representation, care funding, and mobility rights." },
  { name: "Stroke Association", phone: "0303 3033 100", web: "stroke.org.uk", url: "https://www.stroke.org.uk", hours: "Mon-Fri 9am-5pm, Sat 10am-1pm", category: "Neurological & Vascular", desc: "Stroke recovery support, emotional care, and guidance on claiming PIP mobility and daily living components." },
  { name: "Terrence Higgins Trust", phone: "0808 802 1221", web: "tht.org.uk", url: "https://www.tht.org.uk", hours: "Mon-Fri 10am-6pm", category: "Chronic Health & Immunology", desc: "HIV and sexual health charity offering hardship grants, welfare rights advice, and anti-discrimination support." },
  { name: "Thomas Pocklington Trust", phone: "020 8995 0880", web: "pocklington-trust.org.uk", url: "https://www.pocklington-trust.org.uk", hours: "Mon-Fri 9am-5pm", category: "Sensory & Vision", desc: "Advocating for blind and partially sighted people in education, employment, and technology access." },
  { name: "Unique (Rare Chromosome & Gene Disorder Group)", phone: "01883 750000", web: "rarechromo.org", url: "https://www.rarechromo.org", hours: "Mon-Fri 9am-4pm", category: "Genetics & Rare Conditions", desc: "Information and family support network for rare chromosome and gene disorders in children and adults." },
  { name: "Vasculitis UK", phone: "0300 365 0075", web: "vasculitis.org.uk", url: "https://www.vasculitis.org.uk", hours: "Mon-Fri 9am-5pm", category: "Autoimmune & Vascular", desc: "Support for all types of vasculitis, clinical information, peer networks, and disability benefit advice." },
  { name: "Versus Arthritis", phone: "0800 5200 520", web: "versusarthritis.org", url: "https://www.versusarthritis.org", hours: "Mon-Fri 9am-6pm", category: "Musculoskeletal", desc: "Dedicated helpline for arthritis and chronic pain conditions, offering physical activity guides and benefit advice." },
  { name: "Wave Length", phone: "0800 018 2137", web: "wavelength.org.uk", url: "https://wavelength.org.uk", hours: "Mon-Fri 9am-5pm", category: "Isolation & Social Support", desc: "Provides technology and media access to lonely, isolated, or housebound disabled individuals." },
  { name: "Xity / Disability Action", phone: "028 9029 7880", web: "disabilityaction.org", url: "https://www.disabilityaction.org", hours: "Mon-Fri 9am-4:30pm", category: "Regional Advocacy & Rights", desc: "Northern Ireland disability rights charity providing advice on Independent Living Funds and PIP appeals." },
  { name: "YoungMinds", phone: "0808 802 5544", web: "youngminds.org.uk", url: "https://www.youngminds.org.uk", hours: "Mon-Fri 9:30am-4pm", category: "Children & Mental Health", desc: "Leading UK charity fighting for children and young people's mental health and benefits advocacy." },
  { name: "ZipUsIn / Disability Networks", phone: "01202 012345", web: "zipusin.org", url: "https://zipusin.org", hours: "Mon-Fri 9am-5pm", category: "Accessibility & Community", desc: "Community initiative connecting local accessibility services and benefit navigation resources." }
];

// Automatically generate an A-Z object map so components expecting `CHARITIES_BY_LETTER.A` or `SUPPORT_CHARITIES.A` work seamlessly
export const CHARITIES_BY_LETTER = CHARITIES_AZ.reduce((acc, item) => {
  const firstLetter = item.name.trim()[0].toUpperCase();
  if (!acc[firstLetter]) acc[firstLetter] = [];
  acc[firstLetter].push(item);
  return acc;
}, {});

// Export alias guarantees compatibility across all tab components
export const SUPPORT_CHARITIES = CHARITIES_BY_LETTER;
export const disabilitiesAZData = CHARITIES_AZ;
